name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: catbox
    strategy:
      matrix:
        name: [linux, windows]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/catbox
          - name: windows
            os: windows-latest
            artifact_name: target/release/catbox.exe

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies (Linux)
        if: matrix.name == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang mold

      - name: Install Dependencies (Windows)
        if: matrix.name == 'windows'
        run: |
          choco install llvm --version=14.0.0
          choco install mold

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build
        run: cargo build --release --locked

      - name: Make Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.artifact_name }}

  # publish:
  #   name: Publish crate
  #   runs-on: ubuntu-latest
  #   environment: catbox

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install Rust toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         profile: minimal

  #     - name: Publish crate
  #       run: |
  #         cargo login ${{ secrets.CRATES_IO_TOKEN }}
  #         cargo publish
